# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # exit-zero treats all errors as warnings.
        flake8 --config ./linter_config.cfg
    - name: Format with Black
      run: |
        black ./privx_api --check --diff
    - name: Check imports
      run: |
        isort . --settings-path linter_config.cfg -c -v
    - name: Check complexity
      run: |
        radon mi -s -n B .
    - name: Test with pytest
      run: |
        pytest
